name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: pip install tox
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "Running unit tests"
      - run: python3 -m unittest tests/test_restaurant.py
      - run: echo "Running tox"
      - run: tox
      # we could have a deployment like:
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: api-key
      #     heroku_app_name: app-name
      #     heroku_email: your.email@gmail.com
      - run: echo "ğŸ This job's status is ${{ job.status }}."
